apiVersion: v1
kind: Service
metadata:
  name: ${drama}
  labels:
    app: ${drama}
    service: ${drama}
    group: skeleton
spec:
  ports:
  - name: http
    port: 8080
  - name: grpc
    port: 8090
  selector:
    app: ${drama}
    group: skeleton
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ${drama}
spec:
  hosts:
    - "*"
  gateways:
    - nara-gateway
  http:
    - match:
        - uri:
            prefix: /api/${drama}/
      rewrite:
        uri: /
      route:
        - destination:
            host: ${drama}
            port:
              number: 8080
